{
 "title": "Papikos Payment Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Payment Transactions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "papikos_payment_transaction_count_total",
     "legendFormat": "Payments"
    },
    {
     "expr": "papikos_payment_topup_count_total",
     "legendFormat": "Top-ups"
    }
   ]
  },
  {
   "title": "Payment Processing Counts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "papikos_payment_processing_time_seconds_count",
     "legendFormat": "Payment Processing Count"
    }
   ]
  },
  {
   "title": "Average Payment Processing Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "papikos_payment_processing_time_seconds_sum / papikos_payment_processing_time_seconds_count",
     "legendFormat": "Average Processing Time"
    }
   ]
  },
  {
   "title": "Failed Payments",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "papikos_payment_transaction_failed_total",
     "legendFormat": "Failed Payments"
    }
   ]
  }
 ]
}