name: Deploy

on:
  push:
    branches: [ staging ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Grant permission for gradlew
        run: chmod +x gradlew

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Build and push Docker image
        run: |
          ./gradlew bootBuildImage --imageName papikos
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}
          docker tag papikos:latest ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPO }}:latest
          docker push ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPO }}:latest

      - name: Deploy to ECS
        run: |
          aws ecs update-service --cluster ${{ secrets.CLUSTER_NAME }} --service ${{ secrets.SERVICE_NAME }} --force-new-deployment

      - name: Get Public IP Address and Set to DuckDNS
        run: |
          TASK_ARN=$(aws ecs list-tasks --cluster ${{ secrets.CLUSTER_NAME }} --service-name ${{ secrets.SERVICE_NAME }} --query 'taskArns[0]' --output text)
          TASK_DETAILS=$(aws ecs describe-tasks --cluster ${{ secrets.CLUSTER_NAME }} --tasks $TASK_ARN)
          ENI=$(echo $TASK_DETAILS | jq -r '.tasks[0].attachments[0].details[] | select(.name=="networkInterfaceId").value')

          PUBLIC_IP=$(aws ec2 describe-network-interfaces --network-interface-ids $ENI --query 'NetworkInterfaces[0].Association.PublicIp' --output text)
          
          DUCKDNS_TOKEN=${{ secrets.DUCKDNS_TOKEN }}
          DUCKDNS_RESPONSE=$(curl -s "https://www.duckdns.org/update?domains=papikos-a06&token=$DUCKDNS_TOKEN&ip=$PUBLIC_IP&verbose=true")

          echo "## DuckDNS Update Results" >> $GITHUB_STEP_SUMMARY
          echo "* Public IP: $PUBLIC_IP" >> $GITHUB_STEP_SUMMARY
          echo "* Response: $DUCKDNS_RESPONSE" >> $GITHUB_STEP_SUMMARY